### PR TITLE
Add SQL index hints for getPokemon

### PR DESCRIPTION
**Pull request by Mygod**
Let's see if this improves performance.

### CODE REVIEW

**Comment by versx** [comment]
Need to run more tests, getting mixed/same results for the most part. On occasion I've seen it about 1-2 seconds faster but also seen it slower.
With forced index:  
image

Without forced index:  
image

Need more testing from others also if possible.

**Comment by Mygod** [comment]
You are looking at the wrong thing. This PR would not have any impact on rendering time. 🤷

**Comment by versx** [comment]
> You are looking at the wrong thing. This PR would not have any impact on rendering time. 🤷

Oh totally thought it did lol. What does it do then, help with databases with millions of rows?

**Comment by Mygod** [comment]
Look at `get_data` response time.

Old:

image

New:

image

Of course, the more accurate timing should be done at server side.

**Comment by Mygod** [comment]
Just to be completely clear, I was referring to browser rendering time. The overall rendering time would be server processing + client/browser rendering + other crap like network transmission. This PR is supposed to be targeting server processing time.

I just pushed another commit further optimizing the indexing selection.

**Comment by versx** [comment]
> Just to be completely clear, I was referring to browser rendering time. The overall rendering time would be server processing + client/browser rendering + other crap like network transmission. This PR is supposed to be targeting server processing time.
> 
> I just pushed another commit further optimizing the indexing selection.

Thanks for clarifying.

**Comment by Mygod** [comment]
Some further tests show that forcing the index has more or less the same performance as before for our server for both first request and subsequent requests (371±28 ms v.s. 434±92ms; and 69±11 ms v.s. 76±7 ms). However, it fixed the map not loading for some so maybe it is still a good change?

**Comment by versx** [comment]
> Some further tests show that forcing the index has more or less the same performance as before for our server for both first request and subsequent requests (371±28 ms v.s. 434±92ms; and 69±11 ms v.s. 76±7 ms). However, it fixed the map not loading for some so maybe it is still a good change?

I agree, although I'm not so sure if the `updated` check is necessary, since all Pokemon have an updated value maybe it's best if we just force the index on `expire_timestamp` explicitly?

**Comment by Mygod** [comment]
Oh if we do not do that change, the map will be much slower for subsequent requests where `lastUpdate` is set. ~400ms vs ~70ms is definitely statistically significant. If we do not use the check this will be a strictly worse PR for my testing scenarios. 😛

**Pull request merged**
