### PR TITLE
Clear Cache button

### PR DESCRIPTION
**Pull request by Mygod**
~~*untested*~~

*untested on Safari*

Related: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data

### CODE REVIEW

**Comment by Mygod** [comment]
Update: tested and works great.

**Comment by Mygod** [comment]
Maybe a better way to fix this is to instead add a `timestamp` for every resource file too.

**Comment by versx** [comment]
Hmm I tested this, when I clicked Clear-Cache it would sit for about 10 seconds trying to load then eventually refresh the page, but everything looks the same, same filters still selected. 🤔

**Comment by Mygod** [comment]
It happens to me too for some reason. Incognito somehow works fine.

**Comment by Mygod** [comment]
Restarting Chrome somehow also fixed the issue.

**Comment by sketchysocks** [comment]
Working:
- Chrome
- Safari
- Edge
- Android Chrome

Not Working:
- Desktop Firefox

Haven't tested mobile Firefox, Edge, or Safari.

**Comment by Mygod** [comment]
Ready to merge. We can improve this in the future, like add a timestamp (#37).

**Pull request merged**
