### PR TITLE
Refine invasion reward icons

### PR DESCRIPTION
**Pull request by Mygod**
I guess I also accidentally ran eslint. Works on top of #169.

### CODE REVIEW

**Review by clburlison — APPROVED** [review]
10/10. Merge this. Shadow icon is now in bottom left corner but visually it looks and reads better. All the formatting wonkiness is also fixed. Tested with Basic, Home, & Shiny Shuffle icon sets. All look good.

**Comment by Mygod** [comment]
@versx YOU MERGED IN WRONG ORDER

**Comment by versx** [comment]
You said this #172 works on top of #169

**Comment by Mygod** [comment]
facepalm

**Pull request merged**
