### PR TITLE
Clear all site data

### PR DESCRIPTION
**Pull request by versx**
Adds the option to clear cache, cookies, local storage, or all site data.

image

### CODE REVIEW

**Comment by sketchysocks** [comment]
Can we make this configurable? I've had images break in the past if a db connection is dropped for some reason, it's nice to be able to just point them at clearing their cache instead of having to try and walk them through browser settings. Unless you anticipate this may be less of an issue since we're using ~400k less images than RDM 😂 or have different buttons in the Settings menu since there isn't much in the menu itself, just the footer currently.

**Comment by Mygod** [comment]
Just letting you know that `location.reload(true)` only clears cache, also this HTTP header is probably not supported on Safari/iOS.

**Comment by versx** [comment]
> Just letting you know that `location.reload(true)` only clears cache, also this HTTP header is probably not supported on Safari/iOS.

Tested on Catalina via Safari and seemed to work, haven't tested mobile though.

**Comment by versx** [comment]
> > Just letting you know that `location.reload(true)` only clears cache, also this HTTP header is probably not supported on Safari/iOS.
> 
> Tested on Catalina via Safari and seemed to work, haven't tested mobile though.

Nevermind you're right.

**Comment by Mygod** [comment]
https://github.com/versx/MapJS/blob/a9170f1b02228b59e9b8b3f4424d5ea0e9138419/src/views/navbar.mustache#L33

You might have forgotten this. Also you should probably remove other clear buttons for browsers without this header support.

**Pull request merged**
