### PR TITLE
Show a pokestop if its quest OR lure OR invasion matches

### PR DESCRIPTION
**Pull request by Mygod**

### CODE REVIEW

**Comment by versx** [comment]
Looks good, worked well for me. Although enabling the Normal Pokestop filter with Quests: Rare Candy + Poliwag enabled and Invasions: Giovanni enabled it showed quests I wasn't interested in, although you're enabling basically all Pokestops so maybe this is intentional.

**Comment by Mygod** [comment]
That is the intended behavior (also the easy way to implement it). It should at most clutter the map by 2x which is acceptable by my standards (also sometimes the extra information is also good to know).

**Comment by versx** [comment]
> That is the intended behavior (also the easy way to implement it). It should clutter the map by (expected) 2x which is acceptable by my standards (also sometimes the extra information is also good to know).

Gotcha, figured as much. Totally acceptable by me as well, if they are enabling all Normal pokestops they should expect to be bombarded by all of them lol.

**Comment by Mygod** [comment]
Anything blocking this from merging?

**Comment by Mygod** [comment]
I think `getPokemon` probably needs a similar rewrite like this. 🤔

**Comment by darthbutcher** [comment]
> I think `getPokemon` probably needs a similar rewrite like this. 🤔

Not quite the relevant way to do this, but I wasn't sure how else.

1) What is your Discord u/n?
2) Can you take a look at the Pokemon filters not properly being saved unless an IV filter is also selected? You can refresh your page after choosing a Pokemon filter to see an example.

**Pull request merged**
