### PR TITLE
User Configurable Nest Polygons

### LINKED ISSUE #103: Optional nest polygon
Some people think the best polygon is distracting. 🤷‍♂️ Shouldn't be too hard to change this to an optional setting under nests. Low priority.

### PR DESCRIPTION
**Pull request by versx**
Fix #103  
image

### CODE REVIEW

**Review by clburlison — APPROVED** [review]
Working over here. However these icons needs love

**Comment by versx** [comment]
> Working over here. However these icons needs love

Think we should just remove the icons instead?

**Comment by clburlison** [comment]
Heck yeah. Remove the icon & the number (000, 001) columns. Then it's less work  to add new Settings in the future. Thoughts on moving map & icon style into this table instead of bottoms?

**Comment by versx** [comment]
> Heck yeah. Remove the icon & the number (000, 001) columns. Then it's less work to add new Settings in the future. Thoughts on moving map & icon style into this table instead of bottoms?

Awesome I'll do that then, makes more sense. Yeah we could definitely do that, it'd fix the issue of my bad css job that pushes the buttons off screen if the translated text is too long as well lol.

**Pull request merged**
