### PR TITLE
New pokemon iconset

### LINKED ISSUE #116: Support displaying female pokemon
A current list of pokemon/form that has different assets for female version:

```
[ '003_169',
  '003_950',
  '012_959',
  '019_45',
  '020_47',
  '025_598',
  '025_894',
  '025_949',
  '025_2332',
  '026_49',
  '041_157',
  '042_160',
  '044_268',
  '045_271',
  '064_307',
  '065_310',
  '084_1026',
  '085_1029',
  '097_217',
  '111_846',
  '112_849',
  '118_1068',
  '119_1071',
  '123_247',
  '129_253',
  '130_256',
  '154_1124',
  '165_1157',
  '166_1160',
  '178_1193',
  '185_1202',
  '186_244',
  '190_1214',
  '194_1226',
  '195_1229',
  '198_855',
  '202_602',
  '203_1241',
  '207_803',
  '208_905',
  '212_250',
  '214_1262',
  '215_797',
  '217_1268',
  '221_1280',
  '224_1289',
  '229_232',
  '232_1304',
  '255_1358',
  '256_1361',
  '257_1364',
  '267_1382',
  '269_1388',
  '272_1397',
  '274_628',
  '275_631',
  '307_1478',
  '308_1481',
  '315_1502',
  '316_1505',
  '317_1508',
  '322_1517',
  '323_1520',
  '332_613',
  '350_1583',
  '369_1616',
  '396_1658',
  '397_1661',
  '398_1664',
  '399_1667',
  '400_1670',
  '401_1673',
  '402_1676',
  '403_1679',
  '404_1682',
  '405_1685',
  '407_1691',
  '415_1715',
  '417_1721',
  '418_1724',
  '419_1727',
  '424_1742',
  '443_861',
  '444_864',
  '445_867',
  '449_888',
  '450_891',
  '453_1802',
  '454_1805',
  '456_1811',
  '457_1814',
  '459_932',
  '460_935',
  '461_800',
  '464_852',
  '465_1823',
  '473_1838',
  '521_1967',
  '592_2168',
  '593_2171' ]
```

I am writing a script for converting image assets which I might release later.

### PR DESCRIPTION
**Pull request by Mygod**
* Uses pokemon icons from https://github.com/Mygod/pokemon-icon-postprocessor
* Proper support for form, temporary/mega evolution, male/female, costume, shiny pokemon
* Fat pokemon properly displays right above the gym/pokestop, without the extra margin
* Automagic fallback for new pokemon/form/temp evolution/costume
* Dynamic image resolution for filter menu
* Oh also adds `raid_pokemon_costume`

Needs testing.

Fixes #116.

### CODE REVIEW

**Comment by versx** [comment]
Works well so far from my tests. Can see the differences on the map and markers:
image

**Comment by sketchysocks** [comment]
Looking nice and crispy here as well.

**Comment by Mygod** [comment]
Incompatible pokemon naming change:

* For mega evolutions, you need to remove form and add `v`, e.g. `pokemon_icon_003_169_1` -> `pokemon_icon_003_v1`

**Comment by Mygod** [comment]
Example for the new config field: (you only need this field if your icon path is remote)

```json
{
    "icons": {
        "RemotePokemonExample": {
            "path": "https://example.com/pokemon_images",
            "pokemonList": ["001_163", "002_166", ...],
            ...
        }
    }
}
```

**Comment by Mygod** [comment]
@versx Ready to merge with all the caveats listed above.

**Pull request merged**
