### PR TITLE
New config framework

### PR DESCRIPTION
**Pull request by clburlison**
This is my take on PR #168.

- merged `rarity.json` into `default.json`
- `default.json` is now our one source of truth for all config values. These get used as a fallback during updates or if a user doesn't specify a config var.
- `config.example.json` is a bare/semi clean slate on what settings are required
- Using MyGod's basic pokemon icons as the default.

Readme could maybe include more details on how overriding works? Idk seems straightforward to me.

### CODE REVIEW

**Comment by clburlison** [comment]
Additional if this gets merged users can migrate with a simple
`mv src/config.json src/configs.json`. If they have custom rarity settings those will need to be manually merged.

**Comment by Mygod** [comment]
Ba... basic? 😮

**Comment by clburlison** [comment]
basic, standard, pogo official... w/e name you want to use. 🤷  Not shuffle, Home, Derpy, Numbers, or God Awful.

https://raw.githubusercontent.com/ccev/pogoafd/master/sprites/pokemon_icon_025_598.png 😉

**Comment by versx** [comment]
> basic, standard, pogo official... w/e name you want to use. 🤷 Not shuffle, Home, Derpy, Numbers, or God Awful.
> 
> https://raw.githubusercontent.com/ccev/pogoafd/master/sprites/pokemon_icon_025_598.png 😉

image
^^ Official MapJS logo now 😂

**Comment by sketchysocks** [comment]
I believe this is good to go now. Not seeing any issues with my testing 👍

**Pull request merged**
